name: 2 - Workflow CI/CD Terraform


on:
  workflow_dispatch:

jobs:

  Build-Terraform:
    runs-on: ubuntu-latest

    steps:

      - name: Checks-out du repository
        uses: actions/checkout@v2

      # Install the needed version of Terraform cli
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.7

      # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
      - name: Terraform Init
        run: |
          cd ./Terraform/Lab4_Pipeline_CI_CD_Terraform          
          terraform init -backend-config="sas_token=${{ secrets.BACKENDSTORAGESASTOKEN }}"

      # https://www.terraform.io/cli/commands/validate
      - name: Terraform Validate
        run: |
          cd ./Terraform/Lab4_Pipeline_CI_CD_Terraform
          terraform validate

      # Generates an execution plan for Terraform with tfplan file https://www.terraform.io/cli/commands/plan
      - name: Terraform Plan
        run: |
          cd ./Terraform/Lab4_Pipeline_CI_CD_Terraform
          terraform plan -var 'AzureSubscriptionID=${{ secrets.SUBSCRIPTIONID }}' -var 'AzureClientSecret=${{ secrets.CLIENTSECRET }}' -var 'AzureClientID=${{ secrets.CLIENTID }}' -var 'AzureTenandID=${{ secrets.TENANTID }}' -lock=false -out=monplan.tfplan
              
      # apply a execution plan https://www.terraform.io/cli/commands/apply      
      - name: Terraform Apply
        run: |
          cd ./Terraform/Lab4_Pipeline_CI_CD_Terraform
          terraform apply -auto-approve -lock=false "monplan.tfplan"
          
      - name: Checkov GitHub Action
        # You may pin to the exact commit or the version.
        # uses: bridgecrewio/checkov-action@99bb2caf247dfd9f03cf984373bc6043d4e32ebf
        uses: bridgecrewio/checkov-action@v12.1347.0
        with:
          # directory with infrastructure code to scan
          directory: . # optional, default is .
          # Run scan only on a specific check identifier (comma separated)
          #check: # optional
          # Run scan on all checks but a specific check identifier (comma separated)
          #skip_check: # optional
          # display only failed checks
          #quiet: # optional
          # Environment variable name of the Bridgecrew API key from Bridgecrew app
          api-key: c7205e3d-4808-4bd3-bf9b-12a84eb86ecc # optional
          # do not return an error code if there are failed checks
          #soft_fail: # optional
          # run only on a specific infrastructure
          #framework: # optional
          # comma separated list of external (custom) checks directories
          #external_checks_dirs: # optional
          # comma separated list of external (custom) checks repositories
          #external_checks_repos: # optional
          # The format of the output. cli, json, junitxml, github_failed_only, or sarif
          #output_format: # optional, default is sarif
          # download external terraform modules from public git repositories and terraform registry:true, false
          #download_external_modules: # optional
          # log level
          #log_level: # optional, default is WARNING
          # checkov configuration file
          #config_file: # optional
          # Path to a .checkov.baseline file to compare. Report will include only failed checks that are not in the baseline
          #baseline: # optional
          # Do not return an error code only for specific check identifiers (comma separated)
          #soft_fail_on: # optional
          # Return an error code only for specific check identifiers (comma separated)
          #hard_fail_on: # optional
          # Set the username or UID used and optionally the groupname or GID for the action to run under
          #container_user: # optional, default is 0 

